/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts;

import javax.swing.JOptionPane;

/**
 *
 * @author juwit
 */
public class UTS extends javax.swing.JFrame {

    /**
     * Creates new form UTS
     */
    public UTS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbPilih = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        eKomputer = new javax.swing.JTextField();
        bHasil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel2.setText("PERMAINAN BATU GUNTING KERTAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText(":");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 60, 30));

        cbPilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Permainan", "Batu", "Gunting ", "Kertas" }));
        cbPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPilihActionPerformed(evt);
            }
        });
        getContentPane().add(cbPilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 140, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Komputer");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 60, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Pemain");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 60, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText(":");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 60, -1));

        eKomputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eKomputerActionPerformed(evt);
            }
        });
        getContentPane().add(eKomputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 140, 50));

        bHasil.setBackground(new java.awt.Color(203, 125, 125));
        bHasil.setText("Hasil");
        bHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHasilActionPerformed(evt);
            }
        });
        getContentPane().add(bHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Praktikum\\uts.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eKomputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eKomputerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eKomputerActionPerformed

    private void cbPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPilihActionPerformed
       int selectedIndex = cbPilih.getSelectedIndex();
        switch (selectedIndex) {
        case 1:
            eKomputer.setText(String.valueOf("Gunting"));
            break;
            
        case 2:
            eKomputer.setText(String.valueOf("Batu"));
            break;
            
        case 3:
            eKomputer.setText(String.valueOf("Kertas"));
            break;
        default:
            eKomputer.setText(String.valueOf("-"));
            break;   
        }          
    }//GEN-LAST:event_cbPilihActionPerformed

    private void bHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHasilActionPerformed
        String pilih = (String) cbPilih.getSelectedItem();
        int selectedIndex = cbPilih.getSelectedIndex();
        switch (selectedIndex) {
        case 1:
            eKomputer.setText(String.valueOf("Gunting"));
            JOptionPane.showConfirmDialog(this, "ANDA MENANG!");
            break;
            
        case 2:
            eKomputer.setText(String.valueOf("Batu"));
            JOptionPane.showConfirmDialog(this, "ANDA KALAH!");
            break;
            
        case 3:
            eKomputer.setText(String.valueOf("Kertas"));
            JOptionPane.showConfirmDialog(this, "HASIL IMBANG!");
            break;
        default:
            eKomputer.setText(String.valueOf("-"));
            break;   
        }  
        cbPilih.setSelectedIndex(0);
        eKomputer.setText("");
    }//GEN-LAST:event_bHasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UTS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHasil;
    private javax.swing.JComboBox<String> cbPilih;
    private javax.swing.JTextField eKomputer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
